import type { Episode, MemorySignals } from "./types";

const SYNTHETIC_BANNER =
  "SYNTHETIC DEMO DATA — NOT REAL USER EVIDENCE";

const emptyMem = (): MemorySignals => ({
  temporal: ["unknown"],
  spatial: ["unknown"],
  semantic: ["unknown"],
  contextual: [],
  visual: [],
  textual: [],
  social: [],
});

function ep(
  partial: Omit<Episode, "mode" | "synthetic" | "relevance" | "memory"> & {
    memory?: Partial<MemorySignals>;
  },
): Episode {
  const { memory, ...rest } = partial;
  return {
    mode: "demo",
    synthetic: true,
    relevance: "relevant",
    ...rest,
    memory: { ...emptyMem(), ...memory },
    rawText: `${SYNTHETIC_BANNER}\n\n${partial.rawText}`,
  };
}

export const DEMO_EPISODES: Episode[] = [
  ep({
    id: "D01",
    source: "Demo · forum",
    url: "https://example.invalid/demo/d01",
    date: "2026-03-12",
    title: "Cannot find France trip among Best Matches",
    author: "demo-user-a",
    rawText:
      "I know I took hundreds of photos in France last year. I don't remember the month. Searching 'France' used to show every photo from the trip in date order. Now I get a handful of Best Matches and cannot tell which beach day it was.",
    scenario: "Find a specific photo from a remembered country trip without the date",
    remembers: "Country (France); that many trip photos exist; last year (relative)",
    forgot: "Exact month, city, and which day at the beach",
    query: "France",
    searchStrategy: "Single location keyword",
    refinements: "Same word after switching search modes",
    outcome: "partial",
    succeeded: false,
    whyFailed: "Results truncated to a few 'best' items without a dated gallery to scan",
    workaround: "Switch to classic/keyword search to get a chronological list",
    failureCode: "F",
    failureRationale:
      "The user had a valid location clue. The break is ranking/truncation: relevant trip photos are not returned as a complete, time-ordered set.",
    strength: 5,
    archetypeId: "incomplete-set",
    duplicateGroupId: "g-france",
    searchBehaviors: ["Single keyword", "Location search", "Mode switch"],
    memory: {
      temporal: ["year", "relative_time"],
      spatial: ["country", "trip"],
      semantic: ["event"],
      contextual: ["during vacation"],
      visual: ["beach scene"],
    },
  }),
  ep({
    id: "D02",
    source: "Demo · community",
    url: "https://example.invalid/demo/d02",
    date: "2026-01-20",
    title: "Bird species vs six generic birds",
    author: "demo-user-b",
    rawText:
      "I used to search 'kookaburra' and it found the bird. Now nothing. I asked for 'birds' and got 6 photos. I have over 400 bird photos. I need the kookaburra from the backyard, not a random Best Match.",
    scenario: "Retrieve a specific animal photo using species name, then broader class",
    remembers: "Species (kookaburra); backyard context; large bird library",
    forgot: "Date taken",
    query: "kookaburra; then birds",
    searchStrategy: "Specific noun then broader class",
    refinements: "Trial-and-error keyword substitution",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Specific term returned nothing; broad term returned a tiny subset",
    workaround: "Unknown",
    failureCode: "F",
    failureRationale:
      "The user reformulated from species to class. Failure is an incomplete candidate set, not missing memory.",
    strength: 5,
    archetypeId: "incomplete-set",
    duplicateGroupId: "g-birds",
    searchBehaviors: ["Single keyword", "Keyword substitution"],
    memory: {
      temporal: ["unknown"],
      spatial: ["location"],
      semantic: ["animal"],
      contextual: ["backyard"],
      visual: ["bird appearance"],
    },
  }),
  ep({
    id: "D03",
    source: "Demo · review",
    url: "https://example.invalid/demo/d03",
    date: "2025-11-02",
    title: "Dogs expected in reverse chronological order",
    author: "demo-user-c",
    rawText:
      "I searched 'dogs' because I cannot remember which month we got the puppy photos. I expected every dog photo newest first so I could scan. Instead I got a relevance list with no dates showing. I cannot tell which one is the puppy.",
    scenario: "Scan all photos of a pet when the date is forgotten",
    remembers: "Object/animal: dogs; that puppy photos exist",
    forgot: "Month of puppy photos",
    query: "dogs",
    searchStrategy: "Single object keyword expected as a dated filter",
    refinements: "Asked for reverse chronological order in a later attempt",
    outcome: "partial",
    succeeded: false,
    whyFailed: "Relevance ranking removed the time cue needed to recognize the right photo",
    workaround: "Prompt the assistant to sort reverse chronologically",
    failureCode: "G",
    failureRationale:
      "Candidates may exist but recognition fails without dates and a complete list.",
    strength: 5,
    archetypeId: "incomplete-set",
    duplicateGroupId: "g-dogs",
    searchBehaviors: ["Single keyword", "Natural-language sort request"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["animal"],
      visual: ["puppy appearance"],
    },
  }),
  ep({
    id: "D04",
    source: "Demo · forum",
    url: "https://example.invalid/demo/d04",
    date: "2025-09-18",
    title: "Insurance bill by brand name",
    author: "demo-user-d",
    rawText:
      "I photographed my Progressive insurance bill when we moved. I do not remember the date. Searching Progressive used to jump straight to that document. Now I get random photos that are not the bill.",
    scenario: "Find a photographed bill using remembered brand text",
    remembers: "Brand text on a document; moving-house context",
    forgot: "Capture date",
    query: "Progressive",
    searchStrategy: "Text/OCR keyword",
    refinements: "Unknown",
    outcome: "failed",
    succeeded: false,
    whyFailed: "OCR/text match no longer surfaces the document photo",
    workaround: "Unknown",
    failureCode: "D",
    failureRationale:
      "The remembered clue is text in the image. If that text is not searchable, it is a representation gap.",
    strength: 5,
    archetypeId: "ocr-text",
    duplicateGroupId: "g-progressive",
    searchBehaviors: ["Text/OCR search"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["document", "product"],
      contextual: ["while moving house"],
      textual: ["document", "product name"],
    },
  }),
  ep({
    id: "D05",
    source: "Demo · community",
    url: "https://example.invalid/demo/d05",
    date: "2025-08-04",
    title: "Screenshot of a chat message",
    author: "demo-user-e",
    rawText:
      "I screenshot a text message from my sister about the restaurant. I remember a phrase from the message but not when I took the screenshot. Search used to find screenshot text. Now it returns no results. Friends say quotes around the word help.",
    scenario: "Retrieve a screenshot by remembered message wording",
    remembers: "Approximate words in a screenshot; sister; restaurant mention",
    forgot: "Date of screenshot; exact wording",
    query: "phrase from the message (unquoted), then quoted word",
    searchStrategy: "Text/OCR search; later exact-quote syntax",
    refinements: "Added quotation marks",
    outcome: "partial",
    succeeded: null,
    whyFailed: "Unquoted search returned nothing; quote syntax is not obvious",
    workaround: "Put the remembered word in quotation marks",
    failureCode: "B",
    failureRationale:
      "Useful textual memory existed; the user did not know the quote formulation required for exact text.",
    strength: 4,
    archetypeId: "ocr-text",
    duplicateGroupId: "g-screenshot-text",
    searchBehaviors: ["Text/OCR search", "Quoted search"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["screenshot"],
      social: ["family"],
      textual: ["message"],
      contextual: ["restaurant mention"],
    },
  }),
  ep({
    id: "D06",
    source: "Demo · forum",
    url: "https://example.invalid/demo/d06",
    date: "2026-02-11",
    title: "Boarding pass from three years ago",
    author: "demo-user-f",
    rawText:
      "Need the screenshot of my boarding pass from about three years ago. I don't remember the airline date. I searched 'boarding pass'. It used to work instantly.",
    scenario: "Find a travel document screenshot with only document type + relative time",
    remembers: "Document type (boarding pass); relative time (~3 years)",
    forgot: "Exact date, flight number, airline",
    query: "boarding pass",
    searchStrategy: "Document-type keyword",
    refinements: "Unknown",
    outcome: "unknown",
    succeeded: null,
    whyFailed: "Search no longer reliably returns the document class",
    workaround: "Unknown",
    failureCode: "D",
    failureRationale:
      "User remembers document type, not metadata. Retrieval depends on document/OCR indexing.",
    strength: 4,
    archetypeId: "ocr-text",
    duplicateGroupId: "g-boarding",
    searchBehaviors: ["Text/OCR search", "Object keyword"],
    memory: {
      temporal: ["relative_time"],
      spatial: ["trip"],
      semantic: ["document", "screenshot"],
      textual: ["document"],
    },
  }),
  ep({
    id: "D07",
    source: "Demo · workplace anecdote",
    url: "https://example.invalid/demo/d07",
    date: "2025-12-01",
    title: "Supplier name on excavators",
    author: "demo-user-g",
    rawText:
      "A colleague asked for photos of a certain supplier's machinery. I used to type the name painted on the excavators and every matching photo came up. I do not remember which job sites. Now the name search returns nothing.",
    scenario: "Work photos retrieved by painted brand text, not date or site",
    remembers: "Product/brand text on machinery",
    forgot: "Job site dates and locations",
    query: "supplier name",
    searchStrategy: "Text/OCR on signwriting",
    refinements: "Unknown",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Text that used to be indexed is not found",
    workaround: "Unknown",
    failureCode: "D",
    failureRationale:
      "Remembered information is in-image text. Failure is representation, not query wording.",
    strength: 5,
    archetypeId: "ocr-text",
    duplicateGroupId: "g-excavator",
    searchBehaviors: ["Text/OCR search"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["product", "object"],
      textual: ["sign"],
      contextual: ["work"],
    },
  }),
  ep({
    id: "D08",
    source: "Demo · community",
    url: "https://example.invalid/demo/d08",
    date: "2024-06-22",
    title: "Prescription when I was sick last winter",
    author: "demo-user-h",
    rawText:
      "I know I took a picture of the medicine box when I was sick last winter. Searching medicine, January, and the drug name does not find it. I cannot remember if I used the box front or the receipt.",
    scenario: "Medical product photo using episode + guessed drug name",
    remembers: "Episode (sick last winter); medicine box; that a photo exists",
    forgot: "Exact date; exact drug spelling; whether it was box or receipt",
    query: "medicine; January; drug name",
    searchStrategy: "Object + time + text guesses",
    refinements: "Multiple keyword substitutions",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Episodic and textual guesses did not match indexed attributes",
    workaround: "Unknown",
    failureCode: "D",
    failureRationale:
      "User combined episode, month, and product name. Still missed — likely OCR/object labels do not represent the box as remembered.",
    strength: 5,
    archetypeId: "ocr-text",
    duplicateGroupId: "g-medicine",
    searchBehaviors: ["Multiple keywords", "Object + time", "Text/OCR search"],
    memory: {
      temporal: ["season", "month", "relative_time"],
      spatial: ["unknown"],
      semantic: ["product", "document"],
      contextual: ["when sick"],
      textual: ["medicine name"],
    },
  }),
  ep({
    id: "D09",
    source: "Demo · forum",
    url: "https://example.invalid/demo/d09",
    date: "2026-04-02",
    title: "Doctor blocked from searching medical terms",
    author: "demo-user-i",
    rawText:
      "I am a doctor saving my own slide images for breast cancer research. When I search medical terms the app tells me I cannot search that and should talk to a doctor. The photos are mine. Skip AI still pretends there are no matches.",
    scenario: "Owner retrieving their own medical research screenshots",
    remembers: "Medical terms; that slides/screenshots were saved",
    forgot: "Exact filenames",
    query: "medical research terms",
    searchStrategy: "Keyword search of scientific terms",
    refinements: "Skip AI; reword queries",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Safety/policy layer blocked retrieval of the user's own photos",
    workaround: "Turn off AI features (they re-enable)",
    failureCode: "K",
    failureRationale:
      "This is not a memory gap. Policy/safety intercepts a high-stakes retrieval job.",
    strength: 4,
    archetypeId: "policy-vault",
    duplicateGroupId: "g-medical-policy",
    searchBehaviors: ["Keyword search", "Rewording"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["screenshot", "document"],
      textual: ["document"],
      contextual: ["work", "research"],
    },
  }),
  ep({
    id: "D10",
    source: "Demo · forum",
    url: "https://example.invalid/demo/d10",
    date: "2025-10-30",
    title: "Scanned photos of great-grandmother",
    author: "demo-user-j",
    rawText:
      "I scanned black and white photos of my great-grandmother. Most faces were not recognized so searching her name found nothing. I wrote her name in the description field. Now name search works, but it still does not group her as a person.",
    scenario: "Old family scans recalled by relationship, not date or face index",
    remembers: "Person; family relationship; that photos were scanned",
    forgot: "Original dates; faces are not detected",
    query: "great-grandmother's name",
    searchStrategy: "Person name search",
    refinements: "Added captions containing the name",
    outcome: "succeeded",
    succeeded: true,
    whyFailed: "Faces not represented until user wrote names in captions",
    workaround: "Put names in the description field",
    failureCode: "D",
    failureRationale:
      "Social/person memory is strong; face representation is missing on scans.",
    strength: 5,
    archetypeId: "people-index",
    duplicateGroupId: "g-scans-faces",
    searchBehaviors: ["Person search", "Caption workaround"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["person"],
      social: ["family"],
      visual: ["black and white scan"],
    },
  }),
  ep({
    id: "D11",
    source: "Demo · community",
    url: "https://example.invalid/demo/d11",
    date: "2025-08-19",
    title: "Dad, cat, and me in one face group",
    author: "demo-user-k",
    rawText:
      "I remember which photos are of my dad. The face groups mix my dad, my cat, and me as the same person. I can mark it wrong and then it is just untagged. I still cannot put the photo on the correct person.",
    scenario: "Retrieve photos of a parent when identity clusters are wrong",
    remembers: "Who is in the photo (dad)",
    forgot: "How the product assigned groups",
    query: "People & pets / face labels",
    searchStrategy: "Person browse",
    refinements: "Mark incorrect, cannot reassign",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Identity representation is wrong and not manually correctable",
    workaround: "Untag only",
    failureCode: "D",
    failureRationale:
      "Person memory is accurate; the searchable person index is incorrect.",
    strength: 4,
    archetypeId: "people-index",
    duplicateGroupId: "g-face-merge",
    searchBehaviors: ["Person search"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["person", "animal"],
      social: ["family"],
    },
  }),
  ep({
    id: "D12",
    source: "Demo · help community",
    url: "https://example.invalid/demo/d12",
    date: "2023-01-13",
    title: "Name search misses undetected faces",
    author: "demo-user-l",
    rawText:
      "Google hasn't recognised a face and hasn't tagged that person, which means when I search their name the photo doesn't appear. There is no way to add a tag when a face is not detected.",
    scenario: "Known person in a photo that has no detected face",
    remembers: "Person is in the photo",
    forgot: "n/a — detection failed",
    query: "Person name",
    searchStrategy: "Person name search",
    refinements: "Looked for a manual tag setting",
    outcome: "failed",
    succeeded: false,
    whyFailed: "No face in the index, so name cannot retrieve the photo",
    workaround: "Unknown",
    failureCode: "D",
    failureRationale:
      "Primary failure is missing representation of a remembered person.",
    strength: 5,
    archetypeId: "people-index",
    duplicateGroupId: "g-no-face",
    searchBehaviors: ["Person search"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["person"],
      social: ["friend"],
    },
  }),
  ep({
    id: "D13",
    source: "Demo · forum",
    url: "https://example.invalid/demo/d13",
    date: "2022-09-01",
    title: "Find older photo of the same object",
    author: "demo-user-m",
    rawText:
      "I have a recent photo of something very distinct. I am trying to find an older photo of that same item. I have so many photos I cannot find it and I do not remember when I took it. I wanted to search my library using the new photo. Lens searches the internet instead.",
    scenario: "Visual-similarity retrieval from a seed photo when date is unknown",
    remembers: "Visual appearance of a distinct object; has a new photo of it",
    forgot: "When the older photo was taken",
    query: "Wanted reverse-image search inside the library",
    searchStrategy: "Visual similarity / seed photo",
    refinements: "Tried Lens (web results)",
    outcome: "failed",
    succeeded: false,
    whyFailed: "In-library similarity is not the default; visual memory is not a query type",
    workaround: "Later: ask to find more objects like this one (if available)",
    failureCode: "A",
    failureRationale:
      "The user remembers appearance, not metadata, and cannot express it as keywords.",
    strength: 5,
    archetypeId: "visual-similarity",
    duplicateGroupId: "g-like-this",
    searchBehaviors: ["External search/Google Lens", "Visual similarity"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["object"],
      visual: ["object appearance", "distinctive shape"],
    },
  }),
  ep({
    id: "D14",
    source: "Demo · forum",
    url: "https://example.invalid/demo/d14",
    date: "2025-04-17",
    title: "Photos of me as a baby",
    author: "demo-user-n",
    rawText:
      "I searched 'photos of me as a baby'. It said it didn't find any photos of me as a baby. Classic search for 'baby photos' instantly showed the pictures, including the ones I wanted.",
    scenario: "Life-stage + self without dates",
    remembers: "Self; life stage (baby)",
    forgot: "Years of infancy photos",
    query: "photos of me as a baby vs baby photos",
    searchStrategy: "Natural-language then keyword",
    refinements: "Switched to classic keyword",
    outcome: "succeeded",
    succeeded: true,
    whyFailed: "Conversational query misunderstood; simple noun worked",
    workaround: "Classic search with a shorter keyword",
    failureCode: "C",
    failureRationale:
      "Product did not interpret the natural-language life-stage query the way the keyword index could.",
    strength: 5,
    archetypeId: "nl-mismatch",
    duplicateGroupId: "g-baby",
    searchBehaviors: ["Natural-language query", "Single keyword", "Mode switch"],
    memory: {
      temporal: ["relative_time"],
      spatial: ["unknown"],
      semantic: ["person"],
      social: ["family"],
      visual: ["infant appearance"],
    },
  }),
  ep({
    id: "D15",
    source: "Demo · forum",
    url: "https://example.invalid/demo/d15",
    date: "2025-04-17",
    title: "Me in a red dress",
    author: "demo-user-n",
    rawText:
      "I searched 'Me in a red dress'. After a delay it thought I wanted baby pictures again, then showed anyone in a red dress, not me. Classic search showed my red dresses over the years, with my photos first.",
    scenario: "Self + clothing color without a year",
    remembers: "Self; clothing color (red dress)",
    forgot: "Year",
    query: "Me in a red dress",
    searchStrategy: "Person + visual attribute (NL)",
    refinements: "Classic search",
    outcome: "partial",
    succeeded: true,
    whyFailed: "NL bound the wrong entities; color matched other people",
    workaround: "Classic keyword search",
    failureCode: "C",
    failureRationale:
      "Understanding failure on person+attribute binding, contradicted by classic success.",
    strength: 5,
    archetypeId: "nl-mismatch",
    duplicateGroupId: "g-red-dress",
    searchBehaviors: ["Natural-language query", "Person + visual", "Mode switch"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["person"],
      visual: ["clothing", "color"],
      social: ["self"],
    },
  }),
  ep({
    id: "D16",
    source: "Demo · forum",
    url: "https://example.invalid/demo/d16",
    date: "2025-04-18",
    title: "Named Corgi and homemade meals",
    author: "demo-user-n",
    rawText:
      "When I asked for pictures of my Corgi it pulled the photos and mentioned his name and activities. It also found homemade meals I have cooked over the years even though I do not remember dates.",
    scenario: "Successful vague retrieval of pet identity and cooking episode",
    remembers: "Pet identity; that they cook meals",
    forgot: "Specific dates",
    query: "pictures of my Corgi; food I made",
    searchStrategy: "Natural-language person/pet and episode",
    refinements: "None needed",
    outcome: "succeeded",
    succeeded: true,
    whyFailed: "Unknown",
    workaround: "None",
    failureCode: "C",
    failureRationale:
      "Contradiction: NL succeeded for unique pet identity and homemade food episodes.",
    strength: 4,
    archetypeId: "nl-mismatch",
    duplicateGroupId: "g-corgi-success",
    searchBehaviors: ["Natural-language query"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["animal", "food"],
      contextual: ["cooking at home"],
    },
  }),
  ep({
    id: "D17",
    source: "Demo · forum",
    url: "https://example.invalid/demo/d17",
    date: "2025-05-22",
    title: "Arms crossed when I remember nothing else",
    author: "demo-user-o",
    rawText:
      "Gemini can be useful if you are looking for a picture of myself with my arms crossed, when I cannot remember anything else about the photo.",
    scenario: "Pose-only visual memory",
    remembers: "Visual pose (arms crossed); self",
    forgot: "Date, location, event",
    query: "picture of myself with my arms crossed",
    searchStrategy: "Natural-language visual description",
    refinements: "Unknown",
    outcome: "succeeded",
    succeeded: true,
    whyFailed: "Unknown",
    workaround: "None",
    failureCode: "C",
    failureRationale:
      "Contradiction to 'NL always fails': compositional visual queries can succeed.",
    strength: 4,
    archetypeId: "visual-similarity",
    duplicateGroupId: "g-arms",
    searchBehaviors: ["Natural-language query"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["person"],
      visual: ["pose", "composition"],
    },
  }),
  ep({
    id: "D18",
    source: "Demo · community",
    url: "https://example.invalid/demo/d18",
    date: "2026-05-22",
    title: "Wilderness photos with no place name",
    author: "demo-user-p",
    rawText:
      "I have lots of photos out in the wilderness. It is easier to find them on the phone map than to remember the date. They would not have established names under Places.",
    scenario: "Outdoor photos remembered spatially, not by date or Maps name",
    remembers: "Landscape / map location",
    forgot: "Date; official place name",
    query: "Places names; map/heatmap on phone",
    searchStrategy: "Map browsing vs named Places",
    refinements: "Used phone heatmap",
    outcome: "partial",
    succeeded: true,
    whyFailed: "Named place search cannot express unnamed land; desktop map missing",
    workaround: "Mobile map/heatmap",
    failureCode: "A",
    failureRationale:
      "Spatial memory does not translate into a searchable place string.",
    strength: 5,
    archetypeId: "place-unnamed",
    duplicateGroupId: "g-wilderness",
    searchBehaviors: ["Map/location browsing", "Places search"],
    memory: {
      temporal: ["unknown"],
      spatial: ["location"],
      semantic: ["event"],
      visual: ["landscape"],
      contextual: ["wilderness trip"],
    },
  }),
  ep({
    id: "D19",
    source: "Demo · community",
    url: "https://example.invalid/demo/d19",
    date: "2021-02-16",
    title: "Travel photos with GPS off",
    author: "demo-user-q",
    rawText:
      "I took photos last year whilst travelling and did not have location tags turned on. I remember the trip but search by city finds nothing until I add locations by hand.",
    scenario: "Trip memory without GPS",
    remembers: "Trip / travel year",
    forgot: "Embedded location; some city names",
    query: "City names",
    searchStrategy: "Location keyword",
    refinements: "Manually add locations",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Spatial memory is not in metadata",
    workaround: "Manually add location",
    failureCode: "D",
    failureRationale:
      "Location is remembered episodically but not represented in EXIF.",
    strength: 4,
    archetypeId: "place-unnamed",
    duplicateGroupId: "g-gps-off",
    searchBehaviors: ["Location search"],
    memory: {
      temporal: ["year"],
      spatial: ["trip", "city"],
      semantic: ["event"],
      contextual: ["during vacation"],
    },
  }),
  ep({
    id: "D20",
    source: "Demo · community",
    url: "https://example.invalid/demo/d20",
    date: "2026-08-08",
    title: "Location search returns unrelated places",
    author: "demo-user-r",
    rawText:
      "If I search my photos by location now it just pulls photos from all sorts of places. Nothing related to the term I searched. A comment suggested trying 'in London' instead of 'London'.",
    scenario: "City/country string interpreted as something other than GPS place",
    remembers: "Location term",
    forgot: "Which photos belong there",
    query: "London / location keyword; suggested 'in London'",
    searchStrategy: "Location keyword; NL preposition tweak",
    refinements: "in London vs London",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Query understanding mapped the place string to unrelated images",
    workaround: "Disable AI search; try 'in [city]'",
    failureCode: "C",
    failureRationale:
      "The clue was a place name; the product did not treat it as a location filter.",
    strength: 4,
    archetypeId: "nl-mismatch",
    duplicateGroupId: "g-london",
    searchBehaviors: ["Location search", "Natural-language query"],
    memory: {
      temporal: ["unknown"],
      spatial: ["city"],
      semantic: ["other"],
    },
  }),
  ep({
    id: "D21",
    source: "Demo · forum",
    url: "https://example.invalid/demo/d21",
    date: "2026-03-01",
    title: "One photo inside a 1400-picture album",
    author: "demo-user-s",
    rawText:
      "Search shows me which album the picture is in. I open an album with 1400 pics and cannot find the one I remember. Ctrl+F in the album returns 0 even when I can see the photo on screen.",
    scenario: "Know the album; cannot recognize/locate the specific image",
    remembers: "Which album; visual of the photo",
    forgot: "Position in the album; dates of neighboring shots",
    query: "Global search then open album; in-album find",
    searchStrategy: "Album browsing after a successful library hit",
    refinements: "Ctrl+F",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Recognition failure inside a large ordered set",
    workaround: "Favorites; rename on desktop",
    failureCode: "G",
    failureRationale:
      "Retrieval found the haystack. The user cannot identify the needle.",
    strength: 5,
    archetypeId: "recognition-in-set",
    duplicateGroupId: "g-album-1400",
    searchBehaviors: ["Album browsing"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["other"],
      visual: ["scene remembered"],
    },
  }),
  ep({
    id: "D22",
    source: "Demo · forum",
    url: "https://example.invalid/demo/d22",
    date: "2026-03-01",
    title: "Poodles scattered through a dog album",
    author: "demo-user-s",
    rawText:
      "I have 500 dog pictures in an album. I want the 75 poodle pics taken weeks apart. Searching poodles inside the album says 0 results while I am looking at a poodle.",
    scenario: "Subclass (breed) inside a large event/pet album",
    remembers: "Visual class: poodle",
    forgot: "Dates of each poodle photo",
    query: "poodles inside album",
    searchStrategy: "In-album keyword",
    refinements: "None effective",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Album search does not apply object understanding",
    workaround: "Manual paging",
    failureCode: "I",
    failureRationale:
      "Object clue and album context are fragmented; user must connect them manually.",
    strength: 4,
    archetypeId: "recognition-in-set",
    duplicateGroupId: "g-poodles",
    searchBehaviors: ["Album browsing", "Object keyword"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["animal"],
      visual: ["breed appearance"],
    },
  }),
  ep({
    id: "D23",
    source: "Demo · forum",
    url: "https://example.invalid/demo/d23",
    date: "2025-06-01",
    title: "Event photos without time markers in results",
    author: "demo-user-t",
    rawText:
      "I am hunting for pictures from a milestone. I do not remember the exact date. Results are ordered by whatever they think is relevant, with no continuous chronological gallery. Without the marker of time I cannot identify the event.",
    scenario: "Milestone/event retrieval when date is fuzzy",
    remembers: "Event / milestone",
    forgot: "Exact date",
    query: "Event-related keyword in AI ranking",
    searchStrategy: "Keyword + visual scan of ranked results",
    refinements: "Wanted chronological gallery",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Time, the recognition cue, is stripped from results",
    workaround: "Disable AI ranking",
    failureCode: "G",
    failureRationale:
      "Recognition depends on sequence/time, which ranking removes.",
    strength: 5,
    archetypeId: "incomplete-set",
    duplicateGroupId: "g-milestone",
    searchBehaviors: ["Single keyword"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["event"],
      contextual: ["after an event"],
    },
  }),
  ep({
    id: "D24",
    source: "Demo · forum",
    url: "https://example.invalid/demo/d24",
    date: "2025-06-15",
    title: "Fruit varieties I tagged myself",
    author: "demo-user-u",
    rawText:
      "I tagged different varieties of fruit with my own descriptions so I could find them later. AI search does not use those labels. I cannot find anything I filed.",
    scenario: "User-authored captions as the retrieval key",
    remembers: "Custom labels for visually similar objects",
    forgot: "Dates; visual differences the model may not encode",
    query: "Own description text",
    searchStrategy: "Caption/keyword search",
    refinements: "Unknown",
    outcome: "failed",
    succeeded: false,
    whyFailed: "User text not in the retrieval index the AI uses",
    workaround: "Want description search restored",
    failureCode: "D",
    failureRationale:
      "The remembered clue is a caption the product is not searching.",
    strength: 4,
    archetypeId: "user-labels",
    duplicateGroupId: "g-fruit-tags",
    searchBehaviors: ["Caption search"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["food", "object"],
      textual: ["caption"],
    },
  }),
  ep({
    id: "D25",
    source: "Demo · iOS",
    url: "https://example.invalid/demo/d25",
    date: "2025-07-01",
    title: "Renamed videos with keywords",
    author: "demo-user-v",
    rawText:
      "I renamed some videos with keywords to make them easier to find later because I never remember the date. Keyword search no longer finds the names after the new search experience.",
    scenario: "Filename/keywords as a substitute for forgotten dates",
    remembers: "Keywords they assigned",
    forgot: "Native visual attributes and dates",
    query: "Renamed keywords",
    searchStrategy: "Filename/keyword search",
    refinements: "Turn off Gemini",
    outcome: "partial",
    succeeded: true,
    whyFailed: "AI search ignored user-assigned names",
    workaround: "Disable Gemini / classic search",
    failureCode: "D",
    failureRationale:
      "User encoded memory in filenames; representation gap in AI search.",
    strength: 4,
    archetypeId: "user-labels",
    duplicateGroupId: "g-renamed",
    searchBehaviors: ["Caption search", "Mode switch"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["other"],
      textual: ["filename"],
    },
  }),
  ep({
    id: "D26",
    source: "Demo · restaurant",
    url: "https://example.invalid/demo/d26",
    date: "2025-09-05",
    title: "Dish at the hotel restaurant",
    author: "demo-user-w",
    rawText:
      "We want to order the same thing we ate at the hotel in Stanley. I remember the dinner and that I photographed the plate. I do not remember the dish name or the date. Searching 'dinner' and 'hotel' brings too many meals from other trips.",
    scenario: "Food/restaurant episode without dish name or date",
    remembers: "Hotel in Stanley; dinner episode; plate photo exists",
    forgot: "Dish name; exact date",
    query: "dinner; hotel; Stanley",
    searchStrategy: "Place + event keywords",
    refinements: "Tried food, then hotel, then city",
    outcome: "partial",
    succeeded: false,
    whyFailed: "Too many plausible meal photos; cannot isolate that dinner",
    workaround: "Unknown",
    failureCode: "E",
    failureRationale:
      "Clues retrieve a noisy set of similar meals rather than the episode.",
    strength: 4,
    archetypeId: "restaurant-food",
    duplicateGroupId: "g-stanley",
    searchBehaviors: ["Location + event", "Multiple keywords"],
    memory: {
      temporal: ["unknown"],
      spatial: ["location", "city"],
      semantic: ["food", "event"],
      contextual: ["at a hotel restaurant"],
      visual: ["plate / dish appearance"],
    },
  }),
  ep({
    id: "D27",
    source: "Demo · college",
    url: "https://example.invalid/demo/d27",
    date: "2024-11-09",
    title: "College friends at a poorly named venue",
    author: "demo-user-x",
    rawText:
      "I remember a photo with my college friends after someone's birthday. I do not remember the bar name or the year. Searching 'friends' and 'birthday' returns hundreds of parties. Searching names fails because I never labeled faces from that era.",
    scenario: "School/college social memory without year or venue",
    remembers: "College friends; after a birthday; group photo",
    forgot: "Year, venue name, whose birthday",
    query: "friends; birthday; first names",
    searchStrategy: "Social + event keywords; person names",
    refinements: "Tried year guesses (2014, 2015)",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Event class is too broad; people unlabeled",
    workaround: "Timeline scrolling around guessed years",
    failureCode: "I",
    failureRationale:
      "Useful clues (people, event, era) sit in different unconnected indexes.",
    strength: 5,
    archetypeId: "people-index",
    duplicateGroupId: "g-college",
    searchBehaviors: ["Person + event", "Timeline scrolling"],
    memory: {
      temporal: ["relative_time"],
      spatial: ["unknown"],
      semantic: ["person", "event"],
      social: ["friend", "group"],
      contextual: ["at university", "after an event"],
    },
  }),
  ep({
    id: "D28",
    source: "Demo · wedding",
    url: "https://example.invalid/demo/d28",
    date: "2025-02-14",
    title: "Day after a friend's wedding",
    author: "demo-user-y",
    rawText:
      "I am looking for the brunch photos the day after my friend's wedding. I remember the sequence but not the calendar date of the wedding. Searching 'wedding' shows the ceremony, not the next morning. There is no way to say 'the day after'.",
    scenario: "Sequence memory around an event",
    remembers: "Friend's wedding; sequence (the day after); brunch",
    forgot: "Exact wedding date",
    query: "wedding; brunch",
    searchStrategy: "Event keyword; then food",
    refinements: "Could not express sequence",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Sequence/order is remembered but not queryable",
    workaround: "Open wedding photos then manually scroll later",
    failureCode: "A",
    failureRationale:
      "The distinctive memory is sequence, which the user cannot translate into search.",
    strength: 5,
    archetypeId: "sequence-event",
    duplicateGroupId: "g-wedding-plus-one",
    searchBehaviors: ["Event search", "Timeline scrolling"],
    memory: {
      temporal: ["sequence"],
      spatial: ["unknown"],
      semantic: ["event", "food", "person"],
      social: ["friend"],
      contextual: ["after an event"],
    },
  }),
  ep({
    id: "D29",
    source: "Demo · Halloween",
    url: "https://example.invalid/demo/d29",
    date: "2025-10-12",
    title: "Couple's Halloween costume",
    author: "demo-user-z",
    rawText:
      "Complex searches like couple's Halloween costume actually work better for me than searching 'costume'. I did not remember the year. The descriptive query found the matching photos.",
    scenario: "Event + social + clothing description succeeds",
    remembers: "Couple; Halloween; costume look",
    forgot: "Year",
    query: "couple's Halloween costume",
    searchStrategy: "Natural-language multi-attribute",
    refinements: "None",
    outcome: "succeeded",
    succeeded: true,
    whyFailed: "Unknown",
    workaround: "None",
    failureCode: "C",
    failureRationale:
      "Contradiction: descriptive NL can outperform a single noun for event+people+look.",
    strength: 4,
    archetypeId: "nl-mismatch",
    duplicateGroupId: "g-halloween",
    searchBehaviors: ["Natural-language query", "Person + event"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["event", "person"],
      social: ["partner"],
      visual: ["clothing", "costume"],
      contextual: ["Halloween"],
    },
  }),
  ep({
    id: "D30",
    source: "Demo · help community",
    url: "https://example.invalid/demo/d30",
    date: "2025-06-01",
    title: "Search for March with labeled people returns nothing",
    author: "demo-user-aa",
    rawText:
      "I tried looking up March even though I have dated photos. People are labeled. Suggested searches also return no results. Family members' search works. I remember the photos are from March.",
    scenario: "Month as the only temporal clue; index appears broken",
    remembers: "Month (March); people labeled",
    forgot: "Specific contents",
    query: "March",
    searchStrategy: "Date/month search",
    refinements: "Suggested searches; reinstall",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Search index/account issue, not missing memory",
    workaround: "Reinstall / send feedback",
    failureCode: "K",
    failureRationale:
      "Temporal memory was searchable in principle; the index returned nothing.",
    strength: 3,
    archetypeId: "policy-vault",
    duplicateGroupId: "g-march-empty",
    searchBehaviors: ["Date browsing"],
    memory: {
      temporal: ["month"],
      spatial: ["unknown"],
      semantic: ["person"],
    },
  }),
  ep({
    id: "D31",
    source: "Demo · community",
    url: "https://example.invalid/demo/d31",
    date: "2026-08-21",
    title: "Documents in Locked Folder invisible to search",
    author: "demo-user-ab",
    rawText:
      "I tried to look up my locked folder from inside Photos search. It contained private documents I photographed. Search cannot find them. I remembered they were locked but not the new menu location.",
    scenario: "Critical documents exist in a vault that search does not query",
    remembers: "Documents are in Locked Folder",
    forgot: "UI location after redesign",
    query: "Photos search for locked folder / documents",
    searchStrategy: "Keyword search of main library",
    refinements: "Tried web Photos (empty because backup off)",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Library fragmentation: Locked items excluded from search",
    workaround: "Collections → Locked (once told)",
    failureCode: "K",
    failureRationale:
      "The photo exists; the searchable corpus does not include the vault.",
    strength: 4,
    archetypeId: "policy-vault",
    duplicateGroupId: "g-locked",
    searchBehaviors: ["Keyword search"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["document"],
      textual: ["document"],
    },
  }),
  ep({
    id: "D32",
    source: "Demo · scans",
    url: "https://example.invalid/demo/d32",
    date: "2023-08-08",
    title: "Scanned negatives sorted as today",
    author: "demo-user-ac",
    rawText:
      "I am scanning film negatives from the 1970s. I remember they are old family photos, not from this week. After upload they sort as today so searching 1970s finds nothing.",
    scenario: "Old family photos with wrong timestamps",
    remembers: "Era (1970s family)",
    forgot: "Exact original dates; files have upload dates",
    query: "1970s; family",
    searchStrategy: "Year search + people",
    refinements: "Tried to fix dates before upload",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Temporal metadata does not match remembered era",
    workaround: "Exif Date Taken repair before upload",
    failureCode: "D",
    failureRationale:
      "Time is remembered at decade granularity but stored as upload time.",
    strength: 4,
    archetypeId: "wrong-time",
    duplicateGroupId: "g-1970-scans",
    searchBehaviors: ["Date browsing", "Person search"],
    memory: {
      temporal: ["year"],
      spatial: ["unknown"],
      semantic: ["person"],
      social: ["family"],
    },
  }),
  ep({
    id: "D33",
    source: "Demo · Polaroid",
    url: "https://example.invalid/demo/d33",
    date: "2022-09-02",
    title: "Old Polaroid of siblings",
    author: "demo-user-ad",
    rawText:
      "I have an old Polaroid of me and my siblings. I remember who is in it. Search is not identifying our faces. Even if it did I would have tens of thousands of photos to scan per person.",
    scenario: "Sibling group photo from analog scan",
    remembers: "Siblings; that it is a Polaroid",
    forgot: "Date; faces not indexed",
    query: "Person search / Lens",
    searchStrategy: "Person search",
    refinements: "Lens (web)",
    outcome: "failed",
    succeeded: false,
    whyFailed: "No faces + huge person sets even if detected",
    workaround: "External similarity tools",
    failureCode: "D",
    failureRationale:
      "Social memory is strong; face representation and in-set recognition are weak.",
    strength: 5,
    archetypeId: "people-index",
    duplicateGroupId: "g-polaroid",
    searchBehaviors: ["Person search", "External search/Google Lens"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["person"],
      social: ["family"],
      visual: ["Polaroid / analog look"],
    },
  }),
  ep({
    id: "D34",
    source: "Demo · partner library",
    url: "https://example.invalid/demo/d34",
    date: "2025-08-12",
    title: "Whose phone took it",
    author: "demo-user-ae",
    rawText:
      "Our Google Photos library includes my spouse's photos. I remember I took the picture on my phone but not the date. Searching the camera model from Details filters to my shots.",
    scenario: "Partner-shared library; remember device not date",
    remembers: "Own vs spouse photos; device",
    forgot: "Date and distinctive content",
    query: "Exact camera model name",
    searchStrategy: "Metadata string search",
    refinements: "Looked up model in Details",
    outcome: "succeeded",
    succeeded: true,
    whyFailed: "Context (whose camera) is fragmented from content search",
    workaround: "Search camera model",
    failureCode: "I",
    failureRationale:
      "The useful clue (device/owner) is not offered as a first-class filter.",
    strength: 3,
    archetypeId: "context-fragment",
    duplicateGroupId: "g-spouse-camera",
    searchBehaviors: ["Metadata search"],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["other"],
      social: ["partner"],
    },
  }),
  ep({
    id: "D35",
    source: "Demo · warranty",
    url: "https://example.invalid/demo/d35",
    date: "2026-01-05",
    title: "Warranty lives in a photo from 2024",
    author: "demo-user-af",
    rawText:
      "Warranties live in a photo from 2024. Photos search can find 'receipt' sometimes. It never finds 'the thing I still need to do before Thursday.' I remember I photographed the paper, not the date or merchant.",
    scenario: "Utility photo remembered as a pending task, not as a receipt class",
    remembers: "That a warranty/receipt was photographed; a deadline feeling",
    forgot: "Date, merchant, exact words",
    query: "receipt",
    searchStrategy: "Document class keyword",
    refinements: "Cannot search the to-do",
    outcome: "partial",
    succeeded: false,
    whyFailed: "Memory is episodic/task-based; search only has document class",
    workaround: "Unknown",
    failureCode: "A",
    failureRationale:
      "User remembers a life task, not searchable document attributes.",
    strength: 4,
    archetypeId: "ocr-text",
    duplicateGroupId: "g-warranty",
    searchBehaviors: ["Object keyword"],
    memory: {
      temporal: ["year"],
      spatial: ["unknown"],
      semantic: ["document"],
      contextual: ["pending task / warranty"],
      textual: ["document"],
    },
  }),
  ep({
    id: "D36",
    source: "Demo · caption",
    url: "https://example.invalid/demo/d36",
    date: "2025-05-01",
    title: "Caption I just added is not searchable",
    author: "demo-user-ag",
    rawText:
      "I added a caption to a picture of the restaurant so I could find it later. I searched the caption with and without quotes, even paste. Still no luck. I remember the restaurant evening, not the date.",
    scenario: "User tries to make an episodic memory searchable via caption",
    remembers: "Caption text; restaurant evening",
    forgot: "Date",
    query: "Caption words, quoted and unquoted",
    searchStrategy: "Caption search",
    refinements: "Quotes; paste",
    outcome: "failed",
    succeeded: false,
    whyFailed: "Caption not indexed for search",
    workaround: "Unknown",
    failureCode: "D",
    failureRationale:
      "User explicitly encoded memory as text the product did not retrieve.",
    strength: 4,
    archetypeId: "user-labels",
    duplicateGroupId: "g-caption-miss",
    searchBehaviors: ["Caption search", "Quoted search"],
    memory: {
      temporal: ["unknown"],
      spatial: ["location"],
      semantic: ["food", "event"],
      contextual: ["restaurant"],
      textual: ["caption"],
    },
  }),
  ep({
    id: "D37",
    source: "Demo · generic review",
    url: "https://example.invalid/demo/d37",
    date: "2026-01-01",
    title: "Google Photos is terrible",
    author: "demo-user-ah",
    rawText:
      "Google Photos is terrible. The app sucks now. I hate it. One star.",
    scenario: "Unknown",
    remembers: "Unknown",
    forgot: "Unknown",
    query: "Unknown",
    searchStrategy: "Unknown",
    refinements: "Unknown",
    outcome: "unknown",
    succeeded: null,
    whyFailed: "Unknown — no retrieval episode described",
    workaround: "Unknown",
    failureCode: "K",
    failureRationale:
      "Sentiment only. No retrieval task, clues, query, or outcome. Weak evidence.",
    strength: 1,
    archetypeId: "none",
    duplicateGroupId: "g-sentiment",
    searchBehaviors: [],
    memory: {
      temporal: ["unknown"],
      spatial: ["unknown"],
      semantic: ["unknown"],
    },
  }),
];

export const DEMO_IRRELEVANT_ID = "D37";
