from __future__ import annotations

import csv
import json
import os
from typing import Any

BANNER = "DEMO DATA — SYNTHETIC EXAMPLES — NOT REAL USER EVIDENCE"

DEMOS: list[dict[str, Any]] = [
    {
        "id": "D01",
        "source": "Demo · forum",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d01",
        "title": "France trip Best Matches",
        "date": "2026-03-12",
        "author": "demo-user-a",
        "original_quote": "I know I took hundreds of photos in France last year. I don't remember the month. Searching 'France' used to show every photo from the trip in date order. Now I get a handful of Best Matches and cannot tell which beach day it was.",
        "retrieval_scenario": "Find a specific photo from a remembered country trip without the date",
        "remembered_information": "Country (France); many trip photos; last year",
        "forgotten_information": "Exact month, city, which beach day",
        "search_attempt": "France",
        "search_strategy": "location search; keyword search",
        "search_outcome": "partial",
        "failure_category": "Ranking failure",
        "workaround": "Switch to Classic Search",
        "evidence_strength": 5,
        "archetype_id": "incomplete-set",
    },
    {
        "id": "D02",
        "source": "Demo · community",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d02",
        "title": "Kookaburra vs birds",
        "date": "2026-01-08",
        "author": "demo-user-b",
        "original_quote": "I used to search 'kookaburra' and it found the bird. Now nothing. I asked for 'birds' and got 6 photos. I have over 400 bird photos. I need the kookaburra from the backyard, not a random Best Match.",
        "retrieval_scenario": "Retrieve a specific animal photo using species then class",
        "remembered_information": "Species kookaburra; backyard; large bird library",
        "forgotten_information": "Date taken",
        "search_attempt": "kookaburra; then birds",
        "search_strategy": "object search; query reformulation",
        "search_outcome": "failed",
        "failure_category": "Ranking failure",
        "workaround": "Classic Search",
        "evidence_strength": 5,
        "archetype_id": "incomplete-set",
    },
    {
        "id": "D03",
        "source": "Demo · review",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d03",
        "title": "Dogs without dates",
        "date": "2025-11-02",
        "author": "demo-user-c",
        "original_quote": "I searched 'dogs' because I cannot remember which month we got the puppy photos. I expected every dog photo newest first so I could scan. Instead I got a relevance list with no dates showing.",
        "retrieval_scenario": "Scan pet photos when date is forgotten",
        "remembered_information": "Dogs / puppy photos exist",
        "forgotten_information": "Month of puppy photos",
        "search_attempt": "dogs",
        "search_strategy": "object search",
        "search_outcome": "partial",
        "failure_category": "Recognition failure",
        "workaround": "Ask for reverse chronological order",
        "evidence_strength": 5,
        "archetype_id": "incomplete-set",
    },
    {
        "id": "D04",
        "source": "Demo · forum",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d04",
        "title": "Progressive bill",
        "date": "2024-09-18",
        "author": "demo-user-d",
        "original_quote": "I photographed my Progressive insurance bill when we moved. I do not remember the date. Searching Progressive used to jump straight to that document. Now I get random photos that are not the bill.",
        "retrieval_scenario": "Find a photographed bill by remembered brand text",
        "remembered_information": "Brand text Progressive; moving-house context",
        "forgotten_information": "Capture date",
        "search_attempt": "Progressive",
        "search_strategy": "OCR/text search",
        "search_outcome": "failed",
        "failure_category": "Representation gap",
        "workaround": "Unknown",
        "evidence_strength": 5,
        "archetype_id": "text-as-date",
    },
    {
        "id": "D05",
        "source": "Demo · community",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d05",
        "title": "Screenshot message",
        "date": "2024-04-25",
        "author": "demo-user-e",
        "original_quote": "I screenshot a text message from my sister about the restaurant. I remember a phrase from the message but not when I took the screenshot. Search used to find screenshot text. Friends say quotes around the word help.",
        "retrieval_scenario": "Retrieve a screenshot by remembered wording",
        "remembered_information": "Phrase in a screenshot; sister; restaurant",
        "forgotten_information": "Date of screenshot; exact wording",
        "search_attempt": "phrase from the message",
        "search_strategy": "OCR/text search",
        "search_outcome": "partial",
        "failure_category": "Query formulation failure",
        "workaround": "Quoted exact text",
        "evidence_strength": 4,
        "archetype_id": "text-as-date",
    },
    {
        "id": "D06",
        "source": "Demo · forum",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d06",
        "title": "Boarding pass",
        "date": "2026-06-01",
        "author": "demo-user-f",
        "original_quote": "Need the screenshot of my boarding pass from about three years ago. I don't remember the airline date. I searched 'boarding pass'. It used to work instantly.",
        "retrieval_scenario": "Travel document by type + relative time",
        "remembered_information": "Boarding pass screenshot; ~3 years ago",
        "forgotten_information": "Exact date, flight, airline",
        "search_attempt": "boarding pass",
        "search_strategy": "OCR/text search; object search",
        "search_outcome": "unknown",
        "failure_category": "Representation gap",
        "workaround": "Unknown",
        "evidence_strength": 4,
        "archetype_id": "text-as-date",
    },
    {
        "id": "D07",
        "source": "Demo · workplace",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d07",
        "title": "Excavator signwriting",
        "date": "2025-10-14",
        "author": "demo-user-g",
        "original_quote": "A colleague asked for photos of a certain supplier's machinery. I used to type the name painted on the excavators and every matching photo came up. I do not remember which job sites. Now the name search returns nothing.",
        "retrieval_scenario": "Work photos by painted brand text",
        "remembered_information": "Supplier name on machinery",
        "forgotten_information": "Job site dates and locations",
        "search_attempt": "supplier name",
        "search_strategy": "OCR/text search",
        "search_outcome": "failed",
        "failure_category": "Representation gap",
        "workaround": "Unknown",
        "evidence_strength": 5,
        "archetype_id": "text-as-date",
    },
    {
        "id": "D08",
        "source": "Demo · health",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d08",
        "title": "Medicine last year",
        "date": "2025-02-02",
        "author": "demo-user-h",
        "original_quote": "I took a picture of the medicine I was taking last year when I was sick but I don't remember the date. Searching the medicine name isn't finding it.",
        "retrieval_scenario": "Medicine photo from a sickness episode without a date",
        "remembered_information": "Medicine photo; last year; when I was sick",
        "forgotten_information": "Exact date; maybe exact spelling",
        "search_attempt": "medicine name",
        "search_strategy": "OCR/text search; keyword search",
        "search_outcome": "failed",
        "failure_category": "Representation gap",
        "workaround": "Unknown",
        "evidence_strength": 5,
        "archetype_id": "text-as-date",
    },
    {
        "id": "D09",
        "source": "Demo · family",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d09",
        "title": "Great-grandmother scans",
        "date": "2021-08-16",
        "author": "demo-user-i",
        "original_quote": "I scanned black and white photos of my great-grandmother. Most faces were not recognized. I wrote her name in the description so I can search it now.",
        "retrieval_scenario": "Old family scans remembered by relationship",
        "remembered_information": "Great-grandmother; B&W scans",
        "forgotten_information": "Original dates; faces not detected",
        "search_attempt": "her name after captions",
        "search_strategy": "person search",
        "search_outcome": "succeeded",
        "failure_category": "Representation gap",
        "workaround": "Write names in descriptions",
        "evidence_strength": 5,
        "archetype_id": "person-index",
    },
    {
        "id": "D10",
        "source": "Demo · family",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d10",
        "title": "Undetected face",
        "date": "2023-01-13",
        "author": "demo-user-j",
        "original_quote": "I have a few photos where Google hasn't recognised a face. When I search their name the photo doesn't appear. There is no way to tag the missed face.",
        "retrieval_scenario": "Search by remembered person; undetected face excluded",
        "remembered_information": "Person is in the photo",
        "forgotten_information": "n/a — clue is social",
        "search_attempt": "their name",
        "search_strategy": "person search",
        "search_outcome": "failed",
        "failure_category": "Representation gap",
        "workaround": "None in product",
        "evidence_strength": 5,
        "archetype_id": "person-index",
    },
    {
        "id": "D11",
        "source": "Demo · travel",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d11",
        "title": "That place on a map",
        "date": "2023-07-06",
        "author": "demo-user-k",
        "original_quote": "My wife wants 'that picture we took when we went to that place'. I get it in seconds by zooming Google Maps on the area. When I can't find it, I usually didn't use the phone camera.",
        "retrieval_scenario": "Spouse remembers trip/place not date; map zoom retrieves",
        "remembered_information": "Went to a place; a photo was taken",
        "forgotten_information": "Date; often exact venue name",
        "search_attempt": "Google Maps photo map",
        "search_strategy": "location search",
        "search_outcome": "succeeded",
        "failure_category": "Memory-expression failure",
        "workaround": "Map browsing",
        "evidence_strength": 5,
        "archetype_id": "place-without-name",
    },
    {
        "id": "D12",
        "source": "Demo · travel",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d12",
        "title": "Wilderness no place name",
        "date": "2026-05-22",
        "author": "demo-user-l",
        "original_quote": "I have lots of photos out in the wilderness and it's easier to find them on my phone with the map than remembering the date. They would not have established names under Places.",
        "retrieval_scenario": "Wilderness photos: spatial memory, unnamed land",
        "remembered_information": "Landscape / map location",
        "forgotten_information": "Date; official place name",
        "search_attempt": "Places names vs phone map",
        "search_strategy": "location search",
        "search_outcome": "partial",
        "failure_category": "Memory-expression failure",
        "workaround": "Phone heatmap",
        "evidence_strength": 5,
        "archetype_id": "place-without-name",
    },
    {
        "id": "D13",
        "source": "Demo · visual",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d13",
        "title": "Older photo of same object",
        "date": "2022-09-20",
        "author": "demo-user-m",
        "original_quote": "I have a recent photo that has something very distinct in it. I am trying to find an older photo of that same item but I have so many photos I can't find it and I don't remember when I took the photo.",
        "retrieval_scenario": "Seed photo of an object; hunt older photo without date",
        "remembered_information": "Visual appearance of a distinct object; recent photo of it",
        "forgotten_information": "When the older photo was taken",
        "search_attempt": "wanted search using a photo",
        "search_strategy": "Google Lens",
        "search_outcome": "failed",
        "failure_category": "Memory-expression failure",
        "workaround": "Find more like this if available",
        "evidence_strength": 5,
        "archetype_id": "visual-or-episode",
    },
    {
        "id": "D14",
        "source": "Demo · visual",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d14",
        "title": "Arms crossed",
        "date": "2025-06-11",
        "author": "demo-user-n",
        "original_quote": "Gemini can be useful if you're looking for a picture of myself with my arms crossed, when I can't remember anything else about the photo I'm looking for.",
        "retrieval_scenario": "Pose-only visual memory succeeds",
        "remembered_information": "Self; arms crossed pose",
        "forgotten_information": "Date, place, event",
        "search_attempt": "picture of myself with my arms crossed",
        "search_strategy": "natural language",
        "search_outcome": "succeeded",
        "failure_category": "Other",
        "workaround": "none",
        "evidence_strength": 4,
        "archetype_id": "visual-or-episode",
    },
    {
        "id": "D15",
        "source": "Demo · visual",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d15",
        "title": "Me as a baby",
        "date": "2025-04-17",
        "author": "demo-user-o",
        "original_quote": "I searched for 'photos of me as a baby.' Ask said it didn't find any. Classic search for 'baby photos' instantly showed the baby pictures I was looking for.",
        "retrieval_scenario": "Self + life stage without years",
        "remembered_information": "Self as a baby",
        "forgotten_information": "Years of infancy",
        "search_attempt": "photos of me as a baby vs baby photos",
        "search_strategy": "natural language; keyword search",
        "search_outcome": "partial",
        "failure_category": "Product understanding failure",
        "workaround": "Shorter classic keyword",
        "evidence_strength": 5,
        "archetype_id": "visual-or-episode",
    },
    {
        "id": "D16",
        "source": "Demo · album",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d16",
        "title": "1400 album needle",
        "date": "2026-02-01",
        "author": "demo-user-p",
        "original_quote": "I'll open that Album, but I don't know how to easily find ONE particular picture among 1400+ pictures. Ctrl+F shows 0 results even for something I can see in the album.",
        "retrieval_scenario": "Know which album; cannot locate one photo inside it",
        "remembered_information": "Which album; visual of the photo",
        "forgotten_information": "Position in album",
        "search_attempt": "Open album; Ctrl+F",
        "search_strategy": "album browsing; keyword search",
        "search_outcome": "failed",
        "failure_category": "Recognition failure",
        "workaround": "Favorites; rename",
        "evidence_strength": 5,
        "archetype_id": "incomplete-set",
    },
    {
        "id": "D17",
        "source": "Demo · college",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d17",
        "title": "College group photo",
        "date": "2025-08-03",
        "author": "demo-user-q",
        "original_quote": "I know we took a photo after finals in college. I remember who was there but not the year. Searching a friend's name misses the photo because his face isn't tagged.",
        "retrieval_scenario": "College event remembered by people, not year",
        "remembered_information": "Friends present; after finals; college",
        "forgotten_information": "Year",
        "search_attempt": "friend's name",
        "search_strategy": "person search",
        "search_outcome": "failed",
        "failure_category": "Context fragmentation",
        "workaround": "Scroll timeline around remembered era",
        "evidence_strength": 4,
        "archetype_id": "person-index",
    },
    {
        "id": "D18",
        "source": "Demo · wedding",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d18",
        "title": "Day after wedding",
        "date": "2025-05-09",
        "author": "demo-user-r",
        "original_quote": "I want the brunch photos from the morning after the wedding. Searching 'wedding' floods me with ceremony shots. I don't remember the calendar date of the brunch.",
        "retrieval_scenario": "Sequence around an event without the date",
        "remembered_information": "Morning after the wedding; brunch",
        "forgotten_information": "Calendar date",
        "search_attempt": "wedding",
        "search_strategy": "keyword search; trial-and-error",
        "search_outcome": "failed",
        "failure_category": "Result noise",
        "workaround": "Open wedding then scroll later photos",
        "evidence_strength": 4,
        "archetype_id": "incomplete-set",
    },
    {
        "id": "D19",
        "source": "Demo · restaurant",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d19",
        "title": "Restaurant plate",
        "date": "2025-12-01",
        "author": "demo-user-s",
        "original_quote": "We ate somewhere in Goa with a blue plate special. I remember the plate and that it was during the trip, not the restaurant name. Searching 'Goa food' returns hundreds of meals.",
        "retrieval_scenario": "Restaurant memory: trip + visual, not venue name",
        "remembered_information": "Goa trip; blue plate; food",
        "forgotten_information": "Restaurant name; exact date",
        "search_attempt": "Goa food",
        "search_strategy": "location search; object search",
        "search_outcome": "failed",
        "failure_category": "Result noise",
        "workaround": "Manual scroll of trip days",
        "evidence_strength": 4,
        "archetype_id": "place-without-name",
    },
    {
        "id": "D20",
        "source": "Demo · captions",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d20",
        "title": "Caption search fails",
        "date": "2025-07-21",
        "author": "demo-user-t",
        "original_quote": "I added a caption to a picture, then tried to search for the caption. One word, all three words, quotation marks, even paste. Still no luck.",
        "retrieval_scenario": "User encoded a memory as a caption then searched it",
        "remembered_information": "Caption they wrote",
        "forgotten_information": "Date (why they captioned)",
        "search_attempt": "caption words, quotes, paste",
        "search_strategy": "keyword search; trial-and-error",
        "search_outcome": "failed",
        "failure_category": "Representation gap",
        "workaround": "Unknown",
        "evidence_strength": 4,
        "archetype_id": "text-as-date",
    },
    {
        "id": "D21",
        "source": "Demo · success",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d21",
        "title": "Tulips with spouse",
        "date": "2024-05-02",
        "author": "demo-user-u",
        "original_quote": "I wanted a picture of myself and my wife sitting in front of some tulips. I typed that description and found it in 2 minutes.",
        "retrieval_scenario": "Person + scene description without exact date",
        "remembered_information": "Self; wife; tulips; sitting",
        "forgotten_information": "Exact date (fuzzy)",
        "search_attempt": "myself and my wife sitting in front of tulips",
        "search_strategy": "natural language; person search; object search",
        "search_outcome": "succeeded",
        "failure_category": "Other",
        "workaround": "none",
        "evidence_strength": 4,
        "archetype_id": "visual-or-episode",
    },
    {
        "id": "D22",
        "source": "Demo · success",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d22",
        "title": "Corgi and meals",
        "date": "2025-04-17",
        "author": "demo-user-v",
        "original_quote": "When I asked it to show pictures of my Corgi it pulled up the relevant photos and mentioned his name. It also showed homemade meals I've cooked over the years.",
        "retrieval_scenario": "Named pet and cooking episodes without dates",
        "remembered_information": "Corgi; homemade meals over years",
        "forgotten_information": "Specific dates",
        "search_attempt": "pictures of my Corgi; food I made",
        "search_strategy": "natural language",
        "search_outcome": "succeeded",
        "failure_category": "Other",
        "workaround": "none",
        "evidence_strength": 4,
        "archetype_id": "visual-or-episode",
    },
    {
        "id": "D23",
        "source": "Demo · receipts",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d23",
        "title": "Warranty photo 2024",
        "date": "2026-08-01",
        "author": "demo-user-w",
        "original_quote": "Warranties live in a photo from 2024. Photos search can find 'receipt' sometimes. It never finds 'the thing I still need to do before Thursday.'",
        "retrieval_scenario": "Warranty remembered as a pending task, not a receipt class",
        "remembered_information": "Photographed warranty in 2024; still need to act",
        "forgotten_information": "Merchant; which receipt among many",
        "search_attempt": "receipt",
        "search_strategy": "OCR/text search",
        "search_outcome": "failed",
        "failure_category": "Memory-expression failure",
        "workaround": "None reliable",
        "evidence_strength": 4,
        "archetype_id": "text-as-date",
    },
    {
        "id": "D24",
        "source": "Demo · locked",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d24",
        "title": "Locked Folder documents",
        "date": "2026-08-21",
        "author": "demo-user-x",
        "original_quote": "Today I tried to look up my locked folder from inside Photos search and I wasn't able to find it. It contained private and critical documents.",
        "retrieval_scenario": "Documents remembered as Locked Folder contents",
        "remembered_information": "Documents in Locked Folder",
        "forgotten_information": "New UI location",
        "search_attempt": "Photos search for locked folder",
        "search_strategy": "keyword search",
        "search_outcome": "failed",
        "failure_category": "Other",
        "workaround": "Collections → Locked",
        "evidence_strength": 4,
        "archetype_id": "incomplete-set",
    },
    {
        "id": "D25",
        "source": "Demo · two people",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d25",
        "title": "John AND Jane",
        "date": "2019-04-01",
        "author": "demo-user-y",
        "original_quote": "I searched for photos with both John Doe and Jane Doe. Many results showed only one person or an album titled with a birthday. Quoted names AND gave correct results.",
        "retrieval_scenario": "Find photos with two remembered people together",
        "remembered_information": "Two people present",
        "forgotten_information": "Query syntax",
        "search_attempt": "John Doe Jane Doe; quoted AND",
        "search_strategy": "person search; multiple keywords; query reformulation",
        "search_outcome": "succeeded",
        "failure_category": "Query formulation failure",
        "workaround": "Quoted names AND",
        "evidence_strength": 5,
        "archetype_id": "person-index",
    },
    {
        "id": "D26",
        "source": "Demo · GPS off",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d26",
        "title": "Travel last year no GPS",
        "date": "2021-03-11",
        "author": "demo-user-z",
        "original_quote": "I took some photos last year whilst travelling and didn't have location tags turned on. I want to manually add location data so I can find them later.",
        "retrieval_scenario": "Travel photos remembered as last year + trip; GPS off",
        "remembered_information": "Travelling last year",
        "forgotten_information": "Embedded location",
        "search_attempt": "manual location add",
        "search_strategy": "location search",
        "search_outcome": "failed",
        "failure_category": "Representation gap",
        "workaround": "Manually add locations",
        "evidence_strength": 4,
        "archetype_id": "place-without-name",
    },
    {
        "id": "D27",
        "source": "Demo · baby date",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d27",
        "title": "July 2016 baby",
        "date": "2026-07-22",
        "author": "demo-user-aa",
        "original_quote": "I have saved photos from when my child was a baby. I've always been able to search by date, for example 'July 2016,' but now when I do that it says I can't search using those terms.",
        "retrieval_scenario": "Baby photos using month-year because exact day unknown",
        "remembered_information": "Child as baby; July 2016",
        "forgotten_information": "Exact day",
        "search_attempt": "July 2016",
        "search_strategy": "date search; keyword search",
        "search_outcome": "failed",
        "failure_category": "Product understanding failure",
        "workaround": "Unknown",
        "evidence_strength": 5,
        "archetype_id": "incomplete-set",
    },
    {
        "id": "D28",
        "source": "Demo · timeline",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d28",
        "title": "Scroll the year",
        "date": "2025-03-01",
        "author": "demo-user-ab",
        "original_quote": "Google photos app, scroll back to the year/month I'm looking for, look through the photos. Usually it's easier just scrolling to the date if I know roughly when that is.",
        "retrieval_scenario": "Approximate year/month then timeline scroll",
        "remembered_information": "Rough year/season",
        "forgotten_information": "Exact day",
        "search_attempt": "scroll to year/month",
        "search_strategy": "timeline browsing; date search",
        "search_outcome": "succeeded",
        "failure_category": "Other",
        "workaround": "Manually scrolled timeline",
        "evidence_strength": 3,
        "archetype_id": "incomplete-set",
    },
    {
        "id": "D29",
        "source": "Demo · recipes",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d29",
        "title": "Beef ribs among recipes",
        "date": "2024-11-19",
        "author": "demo-user-ac",
        "original_quote": "If I have 100 recipes and I want 'beef ribs' it just brings up them all and I have to open each one. Finding family members is atrocious too. I can type Alan and it brings up pictures of Alex.",
        "retrieval_scenario": "One recipe screenshot among many; person name mismatch",
        "remembered_information": "Dish name beef ribs; person name Alan",
        "forgotten_information": "Which screenshot / date",
        "search_attempt": "beef ribs; Alan",
        "search_strategy": "OCR/text search; person search",
        "search_outcome": "failed",
        "failure_category": "Result noise",
        "workaround": "Open each one",
        "evidence_strength": 5,
        "archetype_id": "text-as-date",
    },
    {
        "id": "D30",
        "source": "Demo · weak",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d30",
        "title": "Generic complaint",
        "date": "2026-01-01",
        "author": "demo-user-ad",
        "original_quote": "Google Photos search is terrible now. I hate it.",
        "retrieval_scenario": "No specific retrieval episode",
        "remembered_information": "Unknown",
        "forgotten_information": "Unknown",
        "search_attempt": "Unknown",
        "search_strategy": "Unknown",
        "search_outcome": "unknown",
        "failure_category": "Other",
        "workaround": "Unknown",
        "evidence_strength": 1,
        "archetype_id": "other",
    },
    {
        "id": "D31",
        "source": "Demo · Halloween",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d31",
        "title": "Halloween costume scene",
        "date": "2025-10-31",
        "author": "demo-user-ae",
        "original_quote": "Ask is better for things like couple's Halloween costume or cat in living room. Worse for a single noun like bird.",
        "retrieval_scenario": "Complex scene vs class noun",
        "remembered_information": "Halloween costume; cat in living room",
        "forgotten_information": "Exact date",
        "search_attempt": "couple's Halloween costume; cat in living room",
        "search_strategy": "natural language",
        "search_outcome": "succeeded",
        "failure_category": "Other",
        "workaround": "Keep Ask for complex terms",
        "evidence_strength": 4,
        "archetype_id": "visual-or-episode",
    },
    {
        "id": "D32",
        "source": "Demo · postcode",
        "source_type": "demo",
        "url": "https://example.invalid/demo/d32",
        "title": "Work visit postcode",
        "date": "2017-04-21",
        "author": "demo-user-af",
        "original_quote": "I search Photos using the postcode of the property. It usually shows photos from that visit. I do about 10 visits a week so I never remember the date.",
        "retrieval_scenario": "Work visits retrieved by postcode not date",
        "remembered_information": "Postcode of property visit",
        "forgotten_information": "Exact date of each visit",
        "search_attempt": "postcode",
        "search_strategy": "location search",
        "search_outcome": "succeeded",
        "failure_category": "Other",
        "workaround": "none",
        "evidence_strength": 5,
        "archetype_id": "place-without-name",
    },
]


def demo_episodes() -> list[dict[str, Any]]:
    out = []
    for d in DEMOS:
        row = dict(d)
        row["synthetic"] = True
        row["verification_status"] = "UNVERIFIED"
        row["ai_interpretation"] = (
            "SYNTHETIC DEMO DATA. This interpretation is for UI exploration only."
        )
        row["original_quote"] = f"{BANNER}\n\n{d['original_quote']}"
        row["temporal_memory"] = d.get("forgotten_information", "")
        row["location_memory"] = d.get("remembered_information", "")
        row["people_memory"] = ""
        row["object_memory"] = d.get("remembered_information", "")
        row["search_behaviors"] = [x.strip() for x in (d.get("search_strategy") or "").split(";") if x.strip()]
        out.append(row)
    return out


def write_demo_csv(path: str = os.path.join("data", "demo_evidence.csv")) -> str:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    rows = demo_episodes()
    fields = [
        "id",
        "source",
        "source_type",
        "url",
        "date",
        "original_quote",
        "retrieval_scenario",
        "remembered_information",
        "forgotten_information",
        "search_attempt",
        "search_strategy",
        "search_outcome",
        "failure_category",
        "workaround",
        "evidence_strength",
        "verification_status",
        "ai_interpretation",
        "synthetic",
    ]
    with open(path, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)
    return path


def load_collected_public_json(path: str = os.path.join("evidence", "retrieval-episodes.json")) -> list[dict[str, Any]]:
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as f:
        raw = json.load(f)
    mapped = []
    fail_map = {
        "MEMORY EXPRESSION": "Memory-expression failure",
        "QUERY FORMULATION": "Query formulation failure",
        "PRODUCT UNDERSTANDING": "Product understanding failure",
        "REPRESENTATION GAP": "Representation gap",
        "RESULT NOISE": "Result noise",
        "RANKING": "Ranking failure",
        "RECOGNITION": "Recognition failure",
        "REFINEMENT": "Refinement failure",
        "CONTEXT FRAGMENTATION": "Context fragmentation",
        "RECOVERY": "Recovery failure",
        "OTHER": "Other",
    }
    for r in raw:
        oc = (r.get("search_outcome") or "").lower()
        if "succeed" in oc and "fail" not in oc:
            outcome = "succeeded"
        elif "fail" in oc or "blocked" in oc:
            outcome = "failed"
        elif "classic" in oc:
            outcome = "partial"
        else:
            outcome = "unknown"
        mapped.append(
            {
                "id": r.get("evidence_id"),
                "source": r.get("source"),
                "source_type": r.get("source_type"),
                "url": r.get("url"),
                "title": r.get("retrieval_scenario"),
                "date": r.get("date"),
                "author": r.get("author"),
                "original_quote": r.get("original_quote"),
                "retrieval_scenario": r.get("retrieval_scenario"),
                "remembered_information": r.get("remembered_information"),
                "forgotten_information": r.get("forgotten_information"),
                "search_attempt": r.get("search_attempt"),
                "search_strategy": r.get("search_strategy"),
                "search_outcome": outcome,
                "failure_category": fail_map.get(r.get("failure_category"), "Other"),
                "workaround": r.get("workaround"),
                "evidence_strength": int(r.get("evidence_strength") or 3),
                "verification_status": "VERIFIED"
                if r.get("verification_status") == "page-fetched"
                else "PARTIALLY VERIFIED",
                "ai_interpretation": r.get("researcher_interpretation"),
                "synthetic": False,
                "temporal_memory": r.get("temporal_memory"),
                "location_memory": r.get("location_memory"),
                "people_memory": r.get("people_memory"),
                "object_memory": r.get("object_memory"),
                "search_behaviors": [r.get("search_strategy") or ""],
                "archetype_id": "",
            }
        )
    return mapped
